Text='''Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum elit nisl, varius eu ipsum eu, accumsan porta mi. Aenean nulla dolor, lobortis quis porttitor nec, rutrum eu erat. Curabitur rhoncus facilisis massa vel eleifend. Sed ut felis ipsum. Etiam eu tempor nisi. Donec quis nisl eget dui volutpat facilisis sit amet vel magna. Fusce erat nisi, ultricies vitae metus in, laoreet varius orci. Nulla sed velit et orci ullamcorper pharetra. In egestas sapien semper lobortis malesuada. Vivamus vitae dolor sed odio iaculis volutpat. Nam dapibus magna quis sodales sodales. Integer pellentesque, arcu et scelerisque convallis, ex orci scelerisque mi, non sagittis turpis nibh eu odio. Cras sit amet euismod quam. Cras vitae urna in nibh facilisis convallis non a sapien. Donec fringilla tincidunt auctor. Mauris vel blandit sem
Nunc ante lacus, suscipit in tempus at, pulvinar in libero. Etiam ut lacus suscipit arcu ullamcorper vulputate. Aenean molestie turpis felis, ac sagittis enim venenatis non. Etiam vel posuere nunc. Phasellus fermentum, est in interdum ullamcorper, massa ligula imperdiet orci, ullamcorper laoreet tellus mi eu ligula. In nec lectus ipsum. Curabitur vehicula sapien sem, laoreet consectetur dui molestie ut. Fusce vitae justo tortor. Donec vulputate tortor nulla, ac aliquam nibh facilisis nec. In bibendum hendrerit diam, sit amet lacinia sem blandit a. Vivamus a vulputate libero, nec congue risus. Mauris ac condimentum sapien, eu vehicula arcu. Cras pellentesque felis sem. In hac habitasse platea dictumst. Vivamus at posuere sem. Nunc ipsum quam, luctus ut odio eget, faucibus feugiat sem.
Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent in magna eu nibh vulputate posuere. Nullam pharetra mi nec tellus porta interdum. Integer fermentum odio nec dui mollis sagittis. Nulla tellus augue, rutrum vitae iaculis eu, rutrum convallis augue. Fusce tempor leo ex, quis lobortis orci condimentum quis. Phasellus eleifend magna sed purus faucibus fermentum. Nunc eget feugiat urna. Morbi nec arcu sed diam volutpat dapibus. Sed at ex et magna venenatis rutrum ac a mauris. Donec molestie scelerisque nibh ac condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt nulla quam, eu maximus augue cursus ultrices. Cras bibendum euismod ante, non bibendum sapien placerat non. Mauris congue venenatis lorem vitae varius. Ut velit ante, condimentum vel volutpat vitae, tincidunt ac ex.
Fusce vitae pulvinar urna, at ornare mi. Mauris eleifend massa at est fermentum ullamcorper. Sed ligula quam, iaculis a blandit a, fermentum vitae mi. Pellentesque ornare orci in lobortis viverra. Fusce convallis suscipit leo. Nullam pulvinar magna a eros aliquam, quis finibus mi ornare. Morbi cursus condimentum elit, quis aliquam felis posuere ac. Nunc aliquam nulla ex, vel aliquam nunc efficitur non. Duis vitae nisl convallis, scelerisque ligula in, dictum urna. Etiam ex lorem, condimentum et justo id, commodo semper erat. Aliquam nec egestas urna, in egestas risus. Pellentesque lacinia malesuada dui. Maecenas id hendrerit mauris. Etiam dignissim varius felis posuere fringilla. Cras mollis accumsan nisi, mattis facilisis leo faucibus a. Mauris semper nec diam a luctus.
Cras tortor velit, commodo ac mi vel, egestas elementum eros. Phasellus in dignissim enim. In posuere nulla sed felis venenatis convallis. Morbi pharetra, arcu vitae vulputate bibendum, justo felis elementum neque, in laoreet est diam ac est. Duis interdum, libero vel dignissim condimentum, purus sapien vulputate lorem, ac pharetra tortor urna non felis. Praesent iaculis dictum mauris, ut sagittis lorem finibus sit amet. Sed sollicitudin interdum velit, sit amet maximus ex egestas quis.
Sed posuere ligula vitae leo tristique bibendum ut eget ante. Mauris feugiat mi in eros maximus, quis gravida urna venenatis. Proin blandit vehicula nulla vitae consequat. Integer quam nibh, aliquam in eros sagittis, auctor vehicula eros. Vestibulum eget ipsum magna. Quisque vitae elit arcu. Maecenas non mi posuere tortor ornare consequat. Cras mi risus, posuere eget turpis et, aliquet tristique leo.
Mauris at imperdiet risus, eget semper est. Aenean lectus diam, rutrum vel posuere vitae, auctor vel velit. Sed dictum neque eget purus rhoncus bibendum. Maecenas blandit tortor porttitor, mollis nisi sed, fermentum risus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla vel massa cursus, auctor lacus vitae, lobortis libero. Praesent vitae felis massa. Aenean volutpat id felis nec egestas. Etiam pretium posuere finibus.
Suspendisse sollicitudin sem at molestie facilisis. Aliquam est est, bibendum ut nunc aliquam, consequat consectetur tortor. Aliquam posuere porta sapien at scelerisque. Curabitur tincidunt mauris nec egestas dapibus. Cras nec lorem condimentum, mattis felis viverra, volutpat dolor. Vivamus molestie, sem eu varius bibendum, tellus nisi tincidunt dui, ac ultricies metus purus ut odio. Quisque a sem rutrum, pretium est eget, mattis velit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus vel egestas ipsum. Vestibulum eleifend gravida nulla sit amet rhoncus. Pellentesque non eros fermentum, ornare ante sed, varius dolor. Donec commodo elit in suscipit facilisis. Mauris libero diam, fermentum eu iaculis et, luctus sit amet dolor. Proin sodales nisl at porta dignissim.
Quisque imperdiet velit ut turpis iaculis volutpat. Pellentesque auctor leo ut dapibus gravida. Vivamus eleifend lacus est, id interdum nibh fermentum eu. Aenean auctor neque et lobortis lacinia. Quisque fermentum rhoncus sapien at venenatis. Aenean est urna, mollis nec tristique quis, molestie vitae arcu. Duis vulputate auctor risus et tristique. Morbi tempor justo in velit lobortis, eu suscipit velit sodales. Cras nunc arcu, consectetur eu accumsan id, tempor et diam. Pellentesque vel metus dolor. Mauris consequat odio in tortor cursus, convallis venenatis augue mattis.
Mauris et magna nulla. In pharetra eget lacus fringilla aliquet. Sed mauris quam, dignissim at justo eget, finibus efficitur tellus. Morbi nec elit suscipit, tempor ante eget, mollis ante. Cras consectetur nisi eu scelerisque porta. Sed iaculis lacus in diam laoreet vehicula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla congue viverra nulla, vitae pulvinar risus commodo ut. In lorem neque, dapibus non nisi et, tempus sollicitudin ligula. Cras nec tempor mi. Aliquam auctor lectus in congue posuere. Sed id urna vitae quam aliquam mollis at a nibh. Suspendisse nec dapibus sem, sed auctor diam. Fusce vestibulum, magna non bibendum malesuada, augue magna egestas eros, quis aliquet est urna eget mi. Suspendisse vitae efficitur nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;
Proin in tortor sed purus suscipit vulputate. Duis in ante sapien. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur varius lorem id hendrerit tincidunt. Donec vel accumsan risus. Phasellus fermentum vel mi id suscipit. Etiam eleifend metus sed velit scelerisque, sed molestie quam fermentum. Fusce tristique elit nec arcu elementum tempus. Pellentesque suscipit ac odio non aliquam. Phasellus dapibus ac neque ac venenatis.
Ut quis ultrices magna, nec dignissim nisi. Etiam non dui condimentum, tempus tellus eget, dapibus dolor. Praesent eu vulputate mi. Etiam augue enim, vehicula eu nisl quis, mattis porta leo. Nam sit amet laoreet ante. Cras at nunc aliquet, tristique nulla eget, lobortis enim. Donec odio dolor, mollis vitae accumsan et, pellentesque vel neque. Interdum et malesuada fames ac ante ipsum primis in faucibus.
Praesent tincidunt euismod augue, vestibulum maximus sem tincidunt eu. Curabitur ornare diam leo, eget iaculis nisl lobortis sed. Praesent consectetur, augue vitae luctus eleifend, risus dui molestie nisl, et aliquet risus libero in dui. Nunc massa nisl, cursus a nibh sit amet, fermentum semper odio. Sed auctor scelerisque eros vehicula sodales. Quisque egestas pellentesque leo, sed imperdiet augue dapibus vel. Aliquam erat volutpat. Sed imperdiet dictum interdum. In velit nisi, tincidunt sed turpis vel, fermentum ultrices urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin elementum, ante non volutpat lacinia, odio orci mattis leo, ut finibus diam magna eu sem. Maecenas egestas ac urna ac fermentum. Mauris quis risus fringilla, pharetra diam vestibulum, tincidunt nunc. Sed eleifend gravida sapien, ut hendrerit erat auctor in. Suspendisse nec blandit neque, eget vulputate magna.
Ut posuere semper venenatis. Sed auctor turpis ornare, consequat nisi sed, tristique velit. Nullam interdum malesuada eros id vehicula. Aenean finibus vehicula scelerisque. Donec aliquet urna felis, et sagittis nulla convallis et. Nulla sit amet urna fringilla, aliquam sem ultricies, sagittis tortor. Suspendisse in mollis dui. Aenean posuere cursus nisl eget hendrerit. Aliquam arcu ex, bibendum vel feugiat sit amet, cursus pharetra tortor. Ut at eleifend sapien. Fusce ac arcu vitae mi facilisis feugiat semper in quam. Aenean eu mollis turpis. Morbi ullamcorper et libero volutpat commodo. Nullam egestas hendrerit elit nec blandit.
Ut gravida tortor nec volutpat scelerisque. Nulla vestibulum nulla neque, eget placerat turpis pharetra non. Etiam in sapien elementum, cursus enim sit amet, blandit tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam erat volutpat. Sed tempor facilisis vulputate. Cras pretium finibus odio id faucibus. Suspendisse imperdiet gravida nisi, a porta diam laoreet sit amet. Proin porttitor eu arcu quis auctor.
Vestibulum sagittis dui eu quam tristique, sit amet tincidunt arcu tempor. Nam vel neque tellus. Morbi sapien massa, laoreet in placerat ac, vehicula non augue. In hac habitasse platea dictumst. Nullam bibendum eget lacus sit amet venenatis. Phasellus sapien arcu, porta in maximus nec, dapibus non nulla. Cras porttitor a risus a malesuada. Nulla facilisi. Ut congue justo eu elementum rhoncus. Mauris dignissim tempus imperdiet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
Sed posuere, erat vel bibendum dapibus, arcu lorem ullamcorper lacus, sit amet elementum velit erat in massa. Integer luctus finibus tincidunt. Etiam sollicitudin dapibus odio eu blandit. Fusce mollis ante in nisi finibus molestie. Pellentesque feugiat felis est, at sagittis ante placerat in. Cras quis placerat mi. Integer venenatis tincidunt faucibus. In metus sem, pellentesque ut bibendum eu, dapibus vitae ante. Suspendisse a scelerisque ex, quis tincidunt risus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec varius erat ac rhoncus hendrerit. Sed vitae justo augue. Suspendisse in imperdiet lacus, ut dictum lorem. Phasellus ac rhoncus metus.
Proin hendrerit porttitor urna vitae pharetra. Aliquam congue, risus ut gravida fringilla, ante risus pulvinar sapien, ac convallis magna erat eget nisi. Aenean in arcu sapien. Morbi at molestie felis. Quisque faucibus vehicula lacus, sed pellentesque est ornare at. Aenean vestibulum, nulla ut porta laoreet, risus urna ornare odio, a tempor nulla tellus vitae massa. Sed at nisl vel nunc luctus auctor. Aenean sit amet orci eu ligula efficitur tristique vel sed arcu. Aliquam aliquet dapibus cursus. Maecenas id sollicitudin turpis. Morbi blandit sollicitudin odio, in vestibulum nibh volutpat eget. Aenean convallis dictum nibh vitae malesuada. Suspendisse convallis et enim vitae porttitor. Vivamus non ullamcorper justo. Nam elementum quam nunc, non convallis velit scelerisque ut.
Nam blandit id arcu a ornare. Sed sed augue consequat, mollis velit non, pretium leo. Nunc ac venenatis erat, eu consequat elit. Nulla facilisi. Vestibulum luctus sodales tincidunt. In pellentesque, turpis eu ultrices tincidunt, nisl risus feugiat felis, sed ornare turpis purus sit amet elit. Praesent congue ipsum ut velit imperdiet, sed sodales lorem laoreet.
Sed faucibus ac neque ut porta. Cras aliquet mi egestas, sagittis velit at, egestas massa. Nam sed justo at dui tincidunt suscipit a quis neque. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis vel sem sit amet est pellentesque accumsan id vel ipsum. Vestibulum vestibulum condimentum dolor quis auctor. Nullam bibendum est in efficitur rutrum. Vivamus mauris nunc, porttitor quis bibendum eu, venenatis a justo. Aliquam blandit tellus in quam feugiat efficitur. Praesent tincidunt metus non maximus gravida. Nullam auctor orci sit amet urna gravida, gravida placerat felis pretium. Aenean nec mi purus. Vestibulum interdum tempor malesuada. Nulla quis convallis massa. Nulla a finibus est, ac gravida ligula. Ut in quam et mauris sollicitudin tincidunt.
Donec tempus dapibus rutrum. Vestibulum at lacus non metus rhoncus placerat. Nulla imperdiet sagittis aliquam. Donec porttitor sed magna eu fermentum. Aenean eget eleifend libero. Ut auctor elit augue, vel ullamcorper justo bibendum quis. Phasellus vel suscipit nisl, sed ultricies nisi. Phasellus et purus accumsan, dignissim massa ac, tincidunt est. In molestie sem sed lacus gravida, non ornare elit posuere. Cras rhoncus ut justo cursus tempus. Nulla gravida arcu vel urna sagittis, ut tincidunt leo finibus. Nulla vel facilisis est. Nulla dictum purus at dolor porta, id eleifend arcu tincidunt.
Duis aliquet pretium mauris, id feugiat turpis feugiat vitae. Curabitur semper est tellus, id mollis velit condimentum vitae. Nullam scelerisque, est sit amet tincidunt volutpat, nulla mi molestie risus, et viverra nisi enim sed nulla. Vestibulum velit metus, congue et ornare vel, elementum.
'''
words=Text.split()

extra ='''



'''

f=open("dummy.h","w")
dmw=0
f.write('const char* dummy['+str(len(words))+']={\n')
for word in words:
    f.write('"'+word+'"')
    dmw+=1
    if(dmw!=len(words)):
        f.write(',\n')
f.write('};')
f.close()
